[workspace]
members = [
  "protocol",
  "protocol-derive"
]

[package]
name = "udp-mud"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "./protocol" }
protocol-derive = { path = "./protocol-derive" }
